REP-26: transition to Candidate
RSS3-Network/REPs pull request #30
Opened 2024-07-19 19:23 UTC by brucexc

https://github.com/RSS3-Network/Whitepaper/pull/7 for the Whitepaper are ready.
https://github.com/NaturalSelectionLabs/RSS3-Network-Contracts/pull/26 contract upgrades are ready.

2024-07-19 20:09 UTC, HenryQW requested changes
run `pnpm format`. I have added the check in #31.

2024-07-19 20:10 UTC, HenryQW commented on REPs/REP-26.md
> +2. RSS3-Network-Contracts code update: <https://github.com/NaturalSelectionLabs/RSS3-Network-Contracts/pull/26>
`Contracts update` should be enough

2024-07-19 21:35 UTC, iavl submitted a review, later dismissed

2024-07-20 15:07 UTC, HenryQW commented on REPs/REP-26.md
> +2. RSS3-Network-Contracts code update: <https://github.com/NaturalSelectionLabs/RSS3-Network-Contracts/pull/26>
still unresolved

2024-07-23 09:01 UTC, iavl approved these changes, later dismissed

2024-07-23 15:33 UTC, HenryQW requested changes

2024-07-23 15:33 UTC, HenryQW commented on REPs/REP-26.md
> +1. Whitepaper: [RSS3-Network/Whitepaper#7](https://github.com/RSS3-Network/Whitepaper/pull/7) and [RSS3-Network/Whitepaper#8](https://github.com/RSS3-Network/Whitepaper/pull/8)
change to list:
1. Whitepaper
    1. [RSS3-Network/Whitepaper#7](https://github.com/RSS3-Network/Whitepaper/pull/7). 
    1.  [RSS3-Network/Whitepaper#8](https://github.com/RSS3-Network/Whitepaper/pull/8)

2024-07-24 03:09 UTC, iavl approved these changes

2024-07-24 03:43 UTC, brucexc commented
Pending contract upgrades, attach updated contracts in the Reference Implementations section.

2024-07-25 14:30 UTC, HenryQW approved these changes

2024-07-25 14:30 UTC, merged